version: '3.8'

services:
  main-server:
    image: ghcr.io/${GITHUB_REPOSITORY}/main-server:latest
    container_name: imweb-main-server
    ports:
      - "80:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - IMWEB_BASE_URL=${IMWEB_BASE_URL}
      - SERVER_BASE_URL=${SERVER_BASE_URL}
    networks:
      - imweb-network
    restart: unless-stopped

networks:
  imweb-network:
    driver: bridge