version: '3.8'

services:
  main-server:
    image: ghcr.io/${GITHUB_REPOSITORY}/main-server:latest
    container_name: imweb-main-server
    ports:
      - "80:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - IMWEB_CLIENT_ID=${IMWEB_CLIENT_ID}
      - IMWEB_CLIENT_SECRET=${IMWEB_CLIENT_SECRET}
      - IMWEB_REDIRECT_URI=${IMWEB_REDIRECT_URI}
    depends_on:
      - mcp-server
    networks:
      - imweb-network
    restart: unless-stopped

  mcp-server:
    image: ghcr.io/${GITHUB_REPOSITORY}/mcp-server:latest
    container_name: imweb-mcp-server
    expose:
      - "8001"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - imweb-network
    restart: unless-stopped

networks:
  imweb-network:
    driver: bridge