version: '3.8'

services:
  main-server:
    image: ghcr.io/${GITHUB_REPOSITORY}/main-server:latest
    container_name: imweb-main-server
    ports:
      - "80:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEB_BASE_URL=${WEB_BASE_URL}
      - SERVER_BASE_URL=${SERVER_BASE_URL}
      - PADDLE_WEBHOOK_SECRET=${PADDLE_WEBHOOK_SECRET}
      - PADDLE_WEBHOOK_STRICT_VERIFY=${PADDLE_WEBHOOK_STRICT_VERIFY}
      - PADDLE_PRICE_ID_MEMBERSHIP=${PADDLE_PRICE_ID_MEMBERSHIP}
      - PADDLE_PRICE_ID_CREDITS=${PADDLE_PRICE_ID_CREDITS}
      - PADDLE_PRODUCT_ID_MEMBERSHIP=${PADDLE_PRODUCT_ID_MEMBERSHIP}
      - PADDLE_PRODUCT_ID_CREDITS=${PADDLE_PRODUCT_ID_CREDITS}
      - CREDITS_UNIT_PRICE_USD=${CREDITS_UNIT_PRICE_USD}
      - PADDLE_API_KEY=${PADDLE_API_KEY}
      - PADDLE_API_BASE_URL=${PADDLE_API_BASE_URL}
    networks:
      - imweb-network
    restart: unless-stopped

networks:
  imweb-network:
    driver: bridge
