version: '3.8'

services:
  main-server:
    image: ghcr.io/${GITHUB_REPOSITORY}/main-server:latest
    container_name: imweb-main-server
    ports:
      - "80:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - IMWEB_CLIENT_ID=${IMWEB_CLIENT_ID}
      - IMWEB_CLIENT_SECRET=${IMWEB_CLIENT_SECRET}
      - IMWEB_REDIRECT_URI=${IMWEB_REDIRECT_URI}
      - PLAYWRIGHT_MCP_SERVER_URL=${PLAYWRIGHT_MCP_SERVER_URL}
      - SERVER_BASE_URL=${SERVER_BASE_URL}
    depends_on:
      - playwright-mcp-server
    networks:
      - imweb-network
    restart: unless-stopped

  playwright-mcp-server:
    image: ghcr.io/${GITHUB_REPOSITORY}/playwright-mcp-server:latest
    container_name: playwright-mcp-server
    expose:
      - "8002"
    environment:
      - NODE_ENV=production
    networks:
      - imweb-network
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    shm_size: 2gb

networks:
  imweb-network:
    driver: bridge