version: '3.8'

services:
  main-server:
    build:
      context: .
      dockerfile: Dockerfile.main
    container_name: imweb-main-server
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mcp-server
    networks:
      - imweb-network
    restart: unless-stopped

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: imweb-mcp-server
    expose:
      - "8001"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - imweb-network
    restart: unless-stopped

networks:
  imweb-network:
    driver: bridge